name: Keep Alive Commit

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */15 * *'  # Runs every 15 days

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_TOKEN }}  # Must be a PAT with push access

      - name: Keep repository alive with timestamp update
        run: |
          echo "Running keep-alive job..."
          date > keepalive.txt
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add keepalive.txt
          git commit -m "Keep-alive commit" || echo "No changes to commit"
          git push
